In [ ]:
import pandas as pd
import numpy as np

np.random.seed(1)

no_of_samples = 1000
class_0_ratio = 0.9
class_1_ratio = 0.1

no_class_0 = int(no_of_samples * class_0_ratio)
no_class_1 = int(no_of_samples * class_1_ratio)

class_0 = {
    'feature1': np.random.normal(0, 1, no_class_0),
    'feature2': np.random.normal(0, 1, no_class_0),
    'target': [0] * no_class_0
}

class_1 = {
    'feature1': np.random.normal(3, 1, no_class_1),
    'feature2': np.random.normal(3, 1, no_class_1),
    'target': [1] * no_class_1
}

x = pd.DataFrame(class_0)
y = pd.DataFrame(class_1)

df = pd.concat([x, y], ignore_index=True)

df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [33]:
df_majority = df[df['target'] == 0]
df_minority = df[df['target'] == 1]

df_majority.shape   # (900, 3)
df_minority.shape   # (100, 3)

(100, 3)

In [ ]:
from sklearn.utils import resample

df_minority_upsampled = resample(
    df_minority,
    replace=True,
    n_samples=len(df_majority),
    random_state=1
)

In [41]:
df_majority_downsampled = resample(
    df_majority,
    replace=False,
    n_samples=len(df_minority),
    random_state=1
)

In [42]:
df_majority_downsampled

     feature1  feature2  target
860 -0.977773  0.872579       0
880  0.309817  1.835870       0
874  0.050317  0.146532       0
780  0.677808 -0.859827       0
525  0.713049  0.320971       0
..        ...       ...     ...
494 -1.579156  2.711950       0
255 -1.044589  0.522655       0
672  0.410266  0.683356       0
481 -1.114871 -0.800787       0
838  0.394428 -0.698571       0

[100 rows x 3 columns]

In [45]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64

In [46]:
# SMOTE synthetic minority oersampling technique 
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000,n_redundant=2,n_clusters_per_class=1,weights=[0.90])

In [47]:
x

array([[-4.15030166e-01,  6.19995079e-01, -7.46178108e-01, ...,
         1.70147308e+00, -1.18054384e-02,  4.88163922e-01],
       [ 2.59381262e-03, -1.06731397e+00,  1.03040628e+00, ...,
         7.66164702e-01,  1.91808531e+00,  1.69209640e+00],
       [-9.30740084e-01,  6.56305529e-01, -3.65391907e-01, ...,
        -2.61136344e+00, -2.54266593e-01,  8.01840260e-01],
       ...,
       [ 2.05507690e+00,  1.47564742e-01,  7.47477178e-01, ...,
        -5.11048684e-01,  8.76355498e-01,  1.28653486e+00],
       [ 3.58560098e-01,  1.21495939e+00, -1.10084383e+00, ...,
         1.81517125e+00,  9.55140563e-02, -1.67753000e+00],
       [ 1.96405128e-01,  1.27299115e+00, -4.88601686e-01, ...,
         6.51226574e-02, -3.96328214e-01, -1.89899380e-01]])

In [48]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [56]:
df_x = pd.DataFrame(x)
df_y = pd.DataFrame(y, columns=['target'])

final_df = pd.concat([df_x, df_y], axis=1)
final_df

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,target
0,-0.415030,0.619995,-0.746178,-0.398061,0.368692,-0.516047,1.504068,-1.631231,-0.398758,1.683467,...,-0.063301,0.967312,0.537106,-0.843792,1.427716,-2.145956,1.701473,-0.011805,0.488164,0
1,0.002594,-1.067314,1.030406,-1.589350,-0.248790,-0.719627,0.048949,-0.601366,-0.298467,-0.874108,...,-1.147528,0.844642,-0.291984,-0.450397,-1.841385,0.456381,0.766165,1.918085,1.692096,0
2,-0.930740,0.656306,-0.365392,0.609000,0.882556,0.005529,-1.282285,-1.474300,-0.396520,-1.139352,...,-1.258187,0.299547,-0.858208,2.969150,-1.262443,-0.706350,-2.611363,-0.254267,0.801840,0
3,-1.245474,-0.007560,0.348809,0.632511,-2.016843,0.156414,-1.154754,-1.116798,-0.316800,-0.603379,...,-0.358213,0.068787,-1.050729,-1.375378,1.671724,1.940959,-0.221171,-0.899979,0.771453,0
4,1.418303,-0.637467,1.751452,1.022537,0.545898,-1.234336,-0.164634,-0.946443,-0.332856,-0.750193,...,-0.628295,1.620439,0.290962,-1.874825,-1.372299,0.391087,-0.449093,-0.143153,1.296531,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1.236715,0.175109,-1.603624,-0.721261,-1.226216,-1.052266,-1.736150,-0.864275,-0.318917,0.843394,...,0.154686,1.056506,1.005745,-0.895077,-0.566002,0.099130,-1.489134,-0.040437,1.333306,0
996,0.861678,-3.014050,1.380265,0.240118,-1.366585,2.222879,-1.042462,-0.563799,-0.273297,0.584174,...,1.511908,0.931296,-0.657687,-0.084693,-0.545891,-0.374171,-0.566524,0.536963,1.521255,0
997,2.055077,0.147565,0.747477,-1.181533,1.417942,1.383253,-0.266079,-0.841307,-0.309306,-0.492864,...,-0.550799,-0.395204,0.273490,-0.828422,-0.209553,-1.078333,-0.511049,0.876355,1.286535,0
998,0.358560,1.214959,-1.100844,0.427257,-0.670918,-0.741407,-1.306705,-0.989880,-0.044278,-1.261558,...,0.578093,-0.335014,1.082128,-0.917692,-0.769345,1.104653,1.815171,0.095514,-1.677530,1
999,0.196405,1.272991,-0.488602,-0.488870,0.874754,-1.944297,0.309180,-1.897287,-0.387904,-1.520890,...,-0.547495,-0.503213,0.660344,-0.048426,0.335618,0.505350,0.065123,-0.396328,-0.189899,0